name: Deploy
on:
  release:
    types: [published]

jobs:
  deploy-executable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["darwin", "linux", "windows"]
        goarch: ["amd64", "arm64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'
      - name: Build and Upload Executable Binary Files
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go build -o "spanner-dump-where-${GOOS}-${GOARCH}" -ldflags "-s -w" -trimpath ./cmd/spanner-dump-where
          zip "spanner-dump-where-${GOOS}-${GOARCH}.zip" "spanner-dump-where-${GOOS}-${GOARCH}"
          gh release upload --clobber "${GITHUB_REF_NAME}" "spanner-dump-where-${GOOS}-${GOARCH}.zip"
